### ISSUE TITLE
Give minimap more threads when available.

### ISSUE THREAD

**Issue by Ge0rges** [wdecoster/chopper#18]
Hello,

I noticed that [here](https://github.com/wdecoster/chopper/blob/c10a757f690318204d6807bc99bcc50d9e61767d/src/main.rs#L167) minimap is only given 8 threads. It would be nice if the threads flag was passed on to minimap.

**Comment by wdecoster** [comment]
That number only affects the building of the index, not the alignment itself. So changing this will not have too much effect. That said, it shouldn't be hardcoded to '8'. Chopper will, at the moment, when a contaminant is being filtered out, not use multithreading. The reason behind this is because it does not support using rayon. This may change in the future, and pull requests are appreciated.

**Comment by Ge0rges** [comment]
I'd be happy to give it a crack though I've never worked with rust. I see rayon is the parallelism library. Any tips before I attempt this?

**Comment by wdecoster** [comment]
Well it shouldn't be done with rayon in this case, as that is not supported for minimap2-rs alignment. There are other options for parallelization, but none that I am sufficiently comfortable with.

**Comment by jelber2** [comment]
Here is an example for parallelization

https://github.com/jguhlin/minimap2-rs/blob/main/fakeminimap2/src/main.rs
