### ISSUE TITLE
sequencing_summary.txt feature

### ISSUE THREAD

**Issue by kenneditodd** [wdecoster/chopper#9]
Hello,

Would be nice if chopper could output a sequencing_summary.txt file similar to guppy. Most QC tools require this file so I am unable to use some of them after using chopper.

**Comment by wdecoster** [comment]
Hmm but since chopper gets only the fastq, a lot of the information in the sequencing_summary.txt file is unavailable. Also, guppy generates a sequencing_summary.txt file since it is a basecaller, while chopper is only filtering the data. You should have a sequencing_summary from your dataset before running chopper, and you want to create a new one afterward? Then you should filter that original sequencing_summary.txt (but that is not supported with chopper). Or did I misunderstand your question?
